name = "channel-manager-bot"
main = "src/index.js"
compatibility_date = "2024-11-01"
compatibility_flags = [ "nodejs_compat" ]

[[kv_namespaces]]
binding = "SESSION_KV"
id = "bb056a585a7a48bcb1a661e93b039d91"
